### ISSUE TITLE
Renaming this repo and npm package

### ISSUE THREAD

**Issue by zeke** [electron/electron-definitelytyped#13]
I think we should rename this repo (and npm package) to `electron-typescript-definitions`, because:

- "Definitely Typed" is the registry for third-party definitions. Could be confusing for folks.
- Putting "typescript" in the name would make it more obvious and discoverable.

Any objections?

**Comment by MarshallOfSound** [comment]
I'm 👍 on this 😄

**Comment by zeke** [comment]
@MarshallOfSound I was gonna publish this to npm under the new name but hit some errors in the process: https://gist.github.com/zeke/fe1292264b25dc08c262cedebc7f17d9

No one is using this, so we can just `npm publish` when we're ready.
