### ISSUE TITLE
No exported reference for the WebViewElement

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron-definitelytyped#3]
We need to somehow export a type definition for the `WebViewElement`  I think this is simply all the `webContents` API's, all the `webPreferences` properties as attributes and all the `webContents` events as `addEventListener` events.

Need to confirm this but I reckon we could set this up to read from those three places and not worry about the docs.

Thoughts @zeke

**Comment by zeke** [comment]
cc @kevinsawicki does that sound right?

**Comment by kevinsawicki** [comment]
> all the webPreferences properties as attributes and all the webContents events as addEventListener events.

Not all of these are supported, but there are 5-10 attributes.

> I think this is simply all the webContents API's,

This is a subset as well, there is a `getWebContents()` method though and ideally in Electron 2.0 we only have that instead of proxying `webContents` methods through `<webview>`.

**Comment by MarshallOfSound** [comment]
Urgh, so we do have to parse the WebView API as it is a dynamic subset of features.  It looks vaguely parseable (different header names).  I think we could just add a new type to `['Class', 'Module', 'Structure']` called `'Element'`.

Does that sound reasonable?

**Comment by zeke** [comment]
https://github.com/electron/electron-docs-linter/pull/85

**Comment by zeke** [comment]
> I think we could just add a new type to ['Class', 'Module', 'Structure'] called 'Element'.

The above PR treats it as a `Class`, but we could easily call it `Element`.

**Comment by zeke** [comment]
Fixed by #4
